DROP DATABASE IF EXISTS haier;

CREATE DATABASE haier DEFAULT CHARACTER SET UTF8 COLLATE utf8_bin;

USE haier;

CREATE TABLE IF NOT EXISTS typeinfo(
	tid INT(2) PRIMARY KEY AUTO_INCREMENT COMMENT '父分类编号',
	tname VARCHAR(20) NOT NULL UNIQUE COMMENT '父分类名称'
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET = utf8 COLLATE = utf8_bin;


CREATE TABLE IF NOT EXISTS ptypeinfo(
	pid INT(2) PRIMARY KEY AUTO_INCREMENT COMMENT '分类编号',
	pname VARCHAR(50) NOT NULL UNIQUE COMMENT '分类名称',
	tid INT(2) COMMENT '父分类编号',								 
	CONSTRAINT FK_ptypeinfo_tid FOREIGN KEY(tid) REFERENCES typeinfo(tid) ON DELETE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS goodsinfo(
	gid INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '商品编号',
	sname VARCHAR(100) NOT NULL UNIQUE COMMENT '商品名称',
	tid INT(2) COMMENT '父分类编号',
	pid INT(2) COMMENT '分类编号',
	price DECIMAL(10,2) NOT NULL COMMENT '商品价格',
	pics VARCHAR(200) NOT NULL COMMENT '商品图片',
	intro VARCHAR(200) NOT NULL COMMENT '商品简介',
	status INT COMMENT '商品状态',
	CONSTRAINT FK_goodsinfo_tid FOREIGN KEY(tid) REFERENCES typeinfo(tid) ON DELETE CASCADE,
	CONSTRAINT FK_ptypeinfo_pid FOREIGN KEY(pid) REFERENCES ptypeinfo(pid) ON DELETE CASCADE
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS activity(
	aid INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '活动编号',
	aname VARCHAR(50) NOT NULL COMMENT '活动名称',
	gid INT(10) COMMENT '商品编号',
	rebate DECIMAL(3,2) NOT NULL COMMENT '折扣',
	sdate DATE NOT NULL COMMENT '活动开始时间',
	edate DATE NOT NULL COMMENT '活动结束时间',
	detail TEXT COMMENT '活动详情',
	status INT COMMENT '活动状态',
	CONSTRAINT FK_goodsinfo_gid FOREIGN KEY(gid) REFERENCES goodsinfo(gid)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS skuinfo(
	sid INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT 'SKU编号',
	gid INT(10) COMMENT '商品编号',
	attrname VARCHAR(10) NOT NULL COMMENT '属性名',
	attrvalue VARCHAR(10) NOT NULL COMMENT '属性值',
	price DECIMAL(10,2) NOT NULL COMMENT '出售价格',
	cost DECIMAL(10,2) NOT NULL COMMENT '成本金额',
	pics VARCHAR(200) NOT NULL COMMENT '商品图片',
	stock INT(2) NOT NULL COMMENT '库存',
	maxStock INT(2) NOT NULL COMMENT '库存上限',
	minSkock INT(2) NOT NULL COMMENT '库存预警线', 
	status INT(2) NOT NULL COMMENT '状态',
	CONSTRAINT FK_goodsinfo_gid2 FOREIGN KEY(gid) REFERENCES goodsinfo(gid)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS admininfo(
	adminId INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '管理员编号',
	aname VARCHAR(100) NOT NULL UNIQUE COMMENT '管理员姓名',
	pwd VARCHAR(100) NOT NULL COMMENT '密码',
	tel VARCHAR(15) UNIQUE COMMENT'联系方式',
	photo VARCHAR(100) 	COMMENT'图像',
	status INT(2) COMMENT '权限'
)ENGINE = InnoDB AUTO_INCREMENT = 100001 DEFAULT  CHARSET = utf8 COLLATE=utf8_bin;

INSERT INTO admininfo VALUES(0, 'navy', md5('123321'), '15873424347', NULL, 1),(0, 'lh', md5(1234), '18374701278', null, 1);


CREATE TABLE IF NOT EXISTS memberinfo(
	mid INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT'会员编号',
	inckName VARCHAR(100) NOT NULL UNIQUE  COMMENT'昵称',
	realName VARCHAR(100) COMMENT'真实姓名',
	tel VARCHAR(15) UNIQUE COMMENT'联系方式',
	email VARCHAR(100) NOT NULL UNIQUE COMMENT'注册邮箱',
	pwd VARCHAR(100) NOT NULL COMMENT'密码',
	photo VARCHAR(100) COMMENT'图像',
	regDate DATETIME COMMENT'注册日期',
	status INT(2) COMMENT'状态'
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT  CHARSET = utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS addressinfo(
	addrId INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT'地址编号',
	mid INT(10) COMMENT '会员编号',
	province VARCHAR(100) NOT NULL COMMENT'省份',
	city VARCHAR(100) NOT NULL COMMENT'城市',
	area VARCHAR(100) NOT NULL COMMENT'区(县)',
	addr VARCHAR(200) COMMENT'详细地址',
	tel VARCHAR(15) UNIQUE COMMENT'联系方式',
	name VARCHAR(100) COMMENT'真实姓名',
	status INT COMMENT '是否为默认地址 是为1',
	CONSTRAINT FK_memberinfo_mid1 FOREIGN KEY(mid) REFERENCES memberinfo(mid)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT  CHARSET = utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS shopcart(
	cartId 	INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '购物车商品项编号',
	mid INT(10) COMMENT '会员编号',
	sid INT(10) COMMENT 'SKU编号',
	num INT(2)  NOT NULL COMMENT '商品数量',
	CONSTRAINT FK_memberinfo_mid2 FOREIGN KEY(mid) REFERENCES memberinfo(mid),
	CONSTRAINT FK_skuinfo_sid1 FOREIGN KEY(sid) REFERENCES skuinfo(sid)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT  CHARSET = utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS orderinfo(
	oid 	INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '订单编号',
	mid INT(10) COMMENT '会员编号',
	total DECIMAL(10,2) NOT NULL COMMENT '商品总价',
	addr VARCHAR(100) 	NOT NULL COMMENT '收货地址',
	status INT(2) COMMENT '订单支付情况',
	orderDate DATE NOT NULL COMMENT '订单生产时间',
	payDate DATE NOT NULL COMMENT '交易时间',
	CONSTRAINT FK_memberinfo_mid3 FOREIGN KEY(mid) REFERENCES memberinfo(mid)
)ENGINE = InnoDB AUTO_INCREMENT = 101 DEFAULT  CHARSET = utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS orderlist(
	orderId 	INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '订单商品项编号',
	oid INT(10) COMMENT '订单编号',
	sid INT(10) COMMENT 'SKU编号',
	num INT(2)  NOT NULL COMMENT '商品数量',
	total DECIMAL(10,2) NOT NULL COMMENT '商品总价',
	profit DECIMAL(10,2) NOT NULL COMMENT '盈利金额',
	user_comment  VARCHAR(2000) COMENT '用户评论',
	status INT COMMENT '评论状态，有/无'
	CONSTRAINT FK_orderinfo_oid FOREIGN KEY(oid) REFERENCES orderinfo(oid),
	CONSTRAINT FK_skuinfo_sid2 FOREIGN KEY(sid) REFERENCES skuinfo(sid)
)ENGINE = InnoDB AUTO_INCREMENT = 100001 DEFAULT  CHARSET = utf8 COLLATE=utf8_bin;
